ALTER TABLE cells DROP COLUMN direction;
ALTER TABLE cells DROP COLUMN info;
ALTER TABLE cells ADD COLUMN info TEXT[] DEFAULT '{}' NOT NULL;
ALTER TABLE cells ADD COLUMN direction TEXT[] DEFAULT '{}' NOT NULL;
